### PR TITLE
Add CFG framework

### PR DESCRIPTION
**Pull request by satabin**
Having a CFG framework would allow for performing nice analyses.

cfg-0

### CODE REVIEW

**Comment by satabin** [comment]
Poke @Jacarte, this is still a WIP, but I'm making progress.

**Comment by Jacarte** [comment]
Thanks @satabin, I will start from this point.

**Comment by satabin** [comment]
Next step is to add graph traversal, and dominator computation. I'll try to make progress on this this weekend.

**Comment by Jacarte** [comment]
We want to use Souper directly, so, we also need an SSA transformation. We can work on it.

**Comment by satabin** [comment]
> We want to use Souper directly, so, we also need an SSA transformation. We can work on it.

Sure, but independently, a graph you cannot traverse is not really useful :)

**Comment by Jacarte** [comment]
Totally agree :)

**Comment by satabin** [comment]
For the SSA part, you can build it on top of this framework, but not sure whether I want to include it int the core module. Maybe a SSA module that depends on `core`, or not included at all, as you can use so many different SSA representations possible.

**Comment by Jacarte** [comment]
Inside the slumps module perhaps. We are implementing it in a separated module. Using the SSA there can be the first step.

**Comment by satabin** [comment]
Agree. We can see in the future, whether it makes sense to integrate it. I'll keep you updated with progress here.

**Comment by satabin** [comment]
@Jacarte I think I am going to merge this one, it contains:
 - CFG building from WASM modules
 - CFG traversal in postorder and reverse postorder
 - immediate dominator computation
 - an example on how to build a CFG for the website

If this is ok for you, I will merge and release it.

**Comment by satabin** [comment]
Release 0.5.0 is on its way to maven central. The example to generate and work with CFG is here: https://swam.gnieh.org/examples/cfg/

**Pull request merged**
