### PR TITLE
Adding log entry separator

### PR DESCRIPTION
**Pull request by Jacarte**
- Added tracer test script (```mill runtime.test.trace```)
- Added log entry separator in config class

### CODE REVIEW

**Comment by satabin** [comment]
This looks good, I completely dropped the separator by inadvertence, sorry for that. Can you please run `mill __.reformat` and `commit --amend` the result?

**Comment by Jacarte** [comment]
Done :)

**Comment by satabin** [comment]
I forgot to tell you to `push --force` to avoid what just happened :D Am I allowed to push to that branch in the PR settings?

**Comment by Jacarte** [comment]
hehehe, my bad, I should know it.

I think you can add commits to the branch, by default I always check the "Allow edits from maintainers"

**Comment by satabin** [comment]
I couldn't push to your branch, so I just merged locally. Thanks for this fix.

**Comment by satabin** [comment]
I just published version `0.5.0-SNAPSHOT` with the tracer. When I am done with the CFG part, I will release 0.5.0.

**Pull request closed without merging**
